// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tzdjcwbvffkszmetufqz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR6ZGpjd2J2ZmZrc3ptZXR1ZnF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc5MDQzNTgsImV4cCI6MjA1MzQ4MDM1OH0.xhLvKlZkyO-sRGCN8ETk-GCO21QGAQT9-9_A5UmdH88";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);